# Background and foreground colors
background = #07150e
foreground = #c3d2c9

# Standard colors
palette = 0=#07150e
palette = 1=#518f6c
palette = 2=#398d60
palette = 3=#468f67
palette = 4=#37946a
palette = 5=#5b9c7b
palette = 6=#5fab85
palette = 7=#c3d2c9

# Bright colors
palette = 8=#676e6a
palette = 9=#6fb788
palette = 10=#55b579
palette = 11=#63b781
palette = 12=#00ad72
palette = 13=#49b684
palette = 14=#4cc58e
palette = 15=#caddd2
