$color = rgba(7, 21, 14, 1)
$inner_color = rgba(7, 21, 14, 0.66)
$outer_color = rgba(91, 156, 123, 1)
$font_color = rgba(195, 210, 201, 1)
$placeholder_color = rgba(195, 210, 201, 0.7)
$check_color = rgba(95, 171, 133, 1)
