background            #07150e
foreground            #c3d2c9

# black
color0  #07150e
color8  #676e6a

# red
color1  #518f6c
color9  #6fb788

# green
color2  #398d60
color10 #55b579

# yellow
color3  #468f67
color11 #63b781

# blue
color4  #37946a
color12 #00ad72

# magenta
color5  #5b9c7b
color13 #49b684

#cyan
color6  #5fab85
color14 #4cc58e

#white
color7  #c3d2c9
color15 #caddd2


